//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ascx {
            get {
                object obj = ResourceManager.GetObject("ascx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;!--Parsed by tree object--&gt;
        ///  &lt;tree&gt;
        ///    &lt;item value=&quot;href&quot;/&gt;
        ///    &lt;item value=&quot;src&quot;/&gt;
        ///    &lt;item value=&quot;imageurl&quot;/&gt;
        ///    &lt;item value=&quot;hoverimageurl&quot;/&gt;
        ///  &lt;/tree&gt;
        ///
        ///  &lt;regex&gt;
        ///    &lt;item value=&quot;[^\s]*\.href\s*=\s*(?&amp;lt;value&amp;gt;[^;|\n|\r|\r\n]+)&quot;/&gt;
        ///    &lt;item value=&quot;[^\s]*\.src\s*=\s*(?&amp;lt;value&amp;gt;[^;|\n|\r|\r\n]+)&quot;/&gt;
        ///    &lt;item value=&quot;[^\s]*\.imageurl\s*=\s*(?&amp;lt;value&amp;gt;[^;|\n|\r|\r\n]+)&quot;/&gt;
        ///    &lt;item value=&quot;[^\s]*\.hoverimageurl\s*=\s*(?&amp;lt;value&amp;gt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AspRegex {
            get {
                return ResourceManager.GetString("AspRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aspx {
            get {
                object obj = ResourceManager.GetObject("aspx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Documents_files_pictogram_symbol_icon_folder {
            get {
                object obj = ResourceManager.GetObject("Documents_files_pictogram_symbol_icon_folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;regex&gt;
        ///    &lt;item value=&quot;[^\s]*\.href\s*=\s*(?&amp;lt;value&amp;gt;[^;|\n|\r|\r\n]+)&quot;/&gt;
        ///    &lt;item value=&quot;[^\s]*\.src\s*=\s*(?&amp;lt;value&amp;gt;[^;|\n|\r|\r\n]+)&quot;/&gt;
        ///    &lt;item value=&quot;[^\s]*\.imageurl\s*=\s*(?&amp;lt;value&amp;gt;[^;|\n|\r|\r\n]+)&quot;/&gt;
        ///    &lt;item value=&quot;[^\s]*\.hoverimageurl\s*=\s*(?&amp;lt;value&amp;gt;[^;|\n|\r|\r\n]+)&quot;/&gt;
        ///
        ///    &lt;item value=&quot;[^\s]*\.attributes.add\(&amp;quot;href&amp;quot;,(?&amp;lt;value&amp;gt;[^\)]+)&quot;/&gt;
        ///    &lt;item value=&quot;[^\s]*\.attributes.add\(&amp;quot;src&amp;quot;,(?&amp;l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DotNetRegex {
            get {
                return ResourceManager.GetString("DotNetRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap excel {
            get {
                object obj = ResourceManager.GetObject("excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap js {
            get {
                object obj = ResourceManager.GetObject("js", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;regex&gt;
        ///    &lt;item value=&quot;[^\s]*\.href\s*=\s*(?&amp;lt;value&amp;gt;[^;|\n|\r|\r\n]+)&quot;/&gt;
        ///    &lt;item value=&quot;[^\s]*\.src\s*=\s*(?&amp;lt;value&amp;gt;[^;|\n|\r|\r\n]+)&quot;/&gt;
        ///    &lt;item value=&quot;[^\s]*\.imageurl\s*=\s*(?&amp;lt;value&amp;gt;[^;|\n|\r|\r\n]+)&quot;/&gt;
        ///    &lt;item value=&quot;[^\s]*\.hoverimageurl\s*=\s*(?&amp;lt;value&amp;gt;[^;|\n|\r|\r\n]+)&quot;/&gt;
        ///
        ///    &lt;item value=&quot;href=&apos;(?&amp;lt;value&amp;gt;[^&apos;]+)&apos;|href=&amp;quot;(?&amp;lt;value&amp;gt;[^&amp;quot;]+)&amp;quot;&quot;/&gt;
        ///    &lt;item value=&quot;src=&apos;(?&amp;lt;value&amp;gt;[^&apos;]+)&apos;|src=&amp;qu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsRegex {
            get {
                return ResourceManager.GetString("JsRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap prj {
            get {
                object obj = ResourceManager.GetObject("prj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sln {
            get {
                object obj = ResourceManager.GetObject("sln", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;item name=&quot;asp&quot; value=&quot;&amp;lt;%= EmbraceResourceManager.GetPathByCulture(&amp;quot;{0}&amp;quot;) %&amp;gt;&quot;/&gt;
        ///  &lt;item name=&quot;common&quot; value=&quot;EmbraceResourceManager.GetPathByCulture(&amp;quot;{0}&amp;quot;)&quot;/&gt;
        ///  &lt;item name=&quot;font&quot; value=&quot;&amp;lt;%= EmbraceResourceManager.GetFontAttribute(&amp;quot;{0}&amp;quot;) %&amp;gt;&quot;/&gt;
        ///&lt;/root&gt;.
        /// </summary>
        internal static string SuggestionPattern {
            get {
                return ResourceManager.GetString("SuggestionPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tick {
            get {
                object obj = ResourceManager.GetObject("tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ukn {
            get {
                object obj = ResourceManager.GetObject("ukn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vb {
            get {
                object obj = ResourceManager.GetObject("vb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
